- build.sbt
- exercise_005_using_and_summon/README.md
- exercise_005_using_and_summon/src/main/resources/application.conf
- exercise_005_using_and_summon/src/main/resources/logback.xml
- exercise_005_using_and_summon/src/main/resources/sudokusolver.conf
- exercise_005_using_and_summon/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercise_005_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/CellMappings.scala
- exercise_005_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/ReductionRules.scala
- exercise_005_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercise_005_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailType.scala
- exercise_005_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuIO.scala
- exercise_005_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercise_005_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercise_005_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercise_005_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolverSettings.scala
- exercise_005_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercise_005_using_and_summon/src/test/resources/logback-test.xml
- exercise_005_using_and_summon/src/test/scala/akkapi/cluster/sudoku/BaseAkkaSpec.scala
- exercise_005_using_and_summon/src/test/scala/akkapi/cluster/sudoku/BaseSpec.scala
- exercise_005_using_and_summon/src/test/scala/akkapi/cluster/sudoku/CellMappingSpec.scala
- exercise_005_using_and_summon/src/test/scala/akkapi/cluster/sudoku/ReductionRuleSpec.scala
- exercise_005_using_and_summon/src/test/scala/akkapi/cluster/sudoku/SudokuDetailProcessorSpec.scala
- exercise_005_using_and_summon/src/test/scala/akkapi/cluster/sudoku/SudokuTestHelpers.scala
Refactored exercises by making use of the following new dotty features
- `usng` - a new syntax for implicit parameters and their arguments. 
- The method `summon` which returns the given instance of a specific type.
> Exercise 5: Contextual abstractions - using and summon

- build.sbt
- exercise_006_givens/README.md
- exercise_006_givens/src/main/resources/application.conf
- exercise_006_givens/src/main/resources/logback.xml
- exercise_006_givens/src/main/resources/sudokusolver.conf
- exercise_006_givens/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercise_006_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/CellMappings.scala
- exercise_006_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/ReductionRules.scala
- exercise_006_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercise_006_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailType.scala
- exercise_006_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuIO.scala
- exercise_006_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercise_006_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercise_006_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercise_006_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolverSettings.scala
- exercise_006_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercise_006_givens/src/test/resources/logback-test.xml
- exercise_006_givens/src/test/scala/akkapi/cluster/sudoku/BaseAkkaSpec.scala
- exercise_006_givens/src/test/scala/akkapi/cluster/sudoku/BaseSpec.scala
- exercise_006_givens/src/test/scala/akkapi/cluster/sudoku/CellMappingSpec.scala
- exercise_006_givens/src/test/scala/akkapi/cluster/sudoku/ReductionRuleSpec.scala
- exercise_006_givens/src/test/scala/akkapi/cluster/sudoku/SudokuDetailProcessorSpec.scala
- exercise_006_givens/src/test/scala/akkapi/cluster/sudoku/SudokuTestHelpers.scala
Refactored exercise using the new dotty feature `given`
> Exercise 6: Contextual abstractions - givens

- exercise_005_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercise_006_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- Apply `using` to sendUpdate in type UpdateSender
- Add alternative approach as a comment in exercise 6
> Refactored exercise 5

- exercise_002_top_level_definitions/README.md
- exercise_003_parameter_untupling/README.md
- exercise_004_extension_methods/README.md
- exercise_005_using_and_summon/README.md
Updated README in the following exercises
- TopLevel definitions
- Parameter untupling
- Extension methods
- Using and summon
> Add instructions for exercises

- exercise_007_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercise_009_union_types/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercise_010_opaque_type_aliases/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercise_011_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- Use more concise definition of givens
> Refactor exercise givens

- exercise_004_parameter_untupling/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercise_005_extension_methods/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercise_006_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercise_007_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercise_009_union_types/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercise_010_opaque_type_aliases/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercise_011_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
* Remove the extra indentation added to code block after applying the new syntax.
> Remove extra indent from exercise parameter untupling

- exercise_000_sudoku_solver_initial_state/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercise_001_dotty_deprecated_syntax_rewriting/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercise_002_dotty_new_syntax_and_indentation_based_syntax/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercise_003_top_level_definitions/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercise_004_parameter_untupling/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercise_005_extension_methods/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercise_006_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercise_007_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercise_009_union_types/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercise_010_opaque_type_aliases/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercise_011_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- Change pattern matching to a match based on a type instead of
matching on a case class instance (as the matched fields aren't
used/needed)
> Improve code readability

- exercises/project/Dependencies.scala
- Move scalatest dependency out of  crossDependencies
> Fix dependency resolution for scalatest

- exercises/exercise_000_sudoku_solver_initial_state/README.md
- exercises/exercise_001_dotty_deprecated_syntax_rewriting/README.md
- exercises/exercise_002_dotty_new_syntax_and_indentation_based_syntax/README.md
- exercises/exercise_003_top_level_definitions/README.md
- exercises/exercise_004_parameter_untupling/README.md
- exercises/exercise_005_extension_methods/README.md
- exercises/exercise_006_using_and_summon/README.md
- exercises/exercise_007_givens/README.md
- exercises/exercise_008_enum_and_export/README.md
- exercises/exercise_009_union_types/README.md
- exercises/exercise_010_opaque_type_aliases/README.md
- exercises/exercise_011_multiversal_equality/README.md
> Update exercise instructions to run the provided tests

- .github/workflows/ci.yml
- Pull course master repo
- Get Course management tools
- Cache SBT and Ivy dependancies
- Generate tests script using CMT
- Runs all possible tests to perform validation
> Add github actions to validate PRs

- .github/workflows/ci.yml
- Release action is triggered only on creating new tags
- Performs tests before release
- Creates studentified and linearized repo
- Upload zip artefacts to release assets
> Add release action to CI

- .github/workflows/ci.yml
- course-management.conf
Adapt gh actions to accommodate  changes in CMT
Ref: https://github.com/lightbend/course-management-tools/pull/90
> Refactor github actions workflow

- .github/workflows/ci.yml
Rename default branch to `main`
> Update actions after default branch name change

- exercises/build.sbt
- exercises/project/Dependencies.scala
0.24.0-RC1 -> 0.24.0 (in fact these are the same apart from the different version name)
> Move to dotty 0.24.0

- .github/workflows/ci.yml
Rename studentified artifact generated along release
> Rename studentified artifact

- README.md
Add a status badge generated by github actions
> Create CI status badge

- exercises/project/MPSelection.scala
- exercises/project/StudentCommandsPlugin.scala
Misspelled `sbtstudent` package name
> Fix package name typo

- exercises/project/Dependencies.scala
- Update dotty version to [0.26.0-RC1](https://github.com/lampepfl/dotty/releases/tag/0.26.0-RC1)
- Update munit version to [0.7.10](https://github.com/scalameta/munit/releases/tag/v0.7.10)
> Upgrade dotty version to 0.26.0-RC1

- exercises/exercise_007_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercises/exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercises/exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_009_union_types/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_009_union_types/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercises/exercise_009_union_types/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_010_opaque_type_aliases/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_010_opaque_type_aliases/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercises/exercise_010_opaque_type_aliases/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_011_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_011_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProgressTracker.scala
- exercises/exercise_011_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/project/Dependencies.scala
- exercises/project/build.properties
- exercises/project/plugins.sbt
- Change to new 'given' syntax
- Add workaround for export bug
> Bump Scala to 3.0.0-M3/Bump munit/sbt/dotty-plugin

- code-snippets/build.sbt
- 3.0.0-RC3 -> 3.0.0 (accidentally reverted to RC3)
> Fix Scala version

- exercises/exercise_000_sudoku_solver_initial_state/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_000_sudoku_solver_initial_state/src/main/scala/org/lunatechlabs/dotty/sudoku/package.scala
- exercises/exercise_001_dotty_deprecated_syntax_rewriting/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_001_dotty_deprecated_syntax_rewriting/src/main/scala/org/lunatechlabs/dotty/sudoku/package.scala
- exercises/exercise_002_dotty_new_syntax_and_indentation_based_syntax/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_002_dotty_new_syntax_and_indentation_based_syntax/src/main/scala/org/lunatechlabs/dotty/sudoku/package.scala
- exercises/exercise_003_top_level_definitions/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_003_top_level_definitions/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_004_parameter_untupling/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_004_parameter_untupling/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_005_extension_methods/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_005_extension_methods/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_006_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_006_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_007_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_007_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_009_union_types/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_009_union_types/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_010_opaque_type_aliases/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_010_opaque_type_aliases/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_011_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuDetailProcessor.scala
- exercises/exercise_011_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- Move definition of field to package/top-level definition
> Refactor code in prep for opaque type aliases exercise

- exercises/exercise_000_sudoku_solver_initial_state/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_000_sudoku_solver_initial_state/src/main/scala/org/lunatechlabs/dotty/sudoku/package.scala
- exercises/exercise_001_dotty_deprecated_syntax_rewriting/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_001_dotty_deprecated_syntax_rewriting/src/main/scala/org/lunatechlabs/dotty/sudoku/package.scala
- exercises/exercise_002_dotty_new_syntax_and_indentation_based_syntax/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_002_dotty_new_syntax_and_indentation_based_syntax/src/main/scala/org/lunatechlabs/dotty/sudoku/package.scala
- exercises/exercise_003_top_level_definitions/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_003_top_level_definitions/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_004_parameter_untupling/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_004_parameter_untupling/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_005_extension_methods/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_005_extension_methods/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_006_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_006_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_007_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_007_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_009_union_types/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_009_union_types/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_010_opaque_type_aliases/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_010_opaque_type_aliases/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_011_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuSolver.scala
- exercises/exercise_011_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- Move case class to top level
> Minor refactoring

- exercises/exercise_000_sudoku_solver_initial_state/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercises/exercise_000_sudoku_solver_initial_state/src/main/scala/org/lunatechlabs/dotty/sudoku/package.scala
- exercises/exercise_001_dotty_deprecated_syntax_rewriting/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercises/exercise_001_dotty_deprecated_syntax_rewriting/src/main/scala/org/lunatechlabs/dotty/sudoku/package.scala
- exercises/exercise_002_dotty_new_syntax_and_indentation_based_syntax/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercises/exercise_002_dotty_new_syntax_and_indentation_based_syntax/src/main/scala/org/lunatechlabs/dotty/sudoku/package.scala
- exercises/exercise_003_top_level_definitions/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercises/exercise_003_top_level_definitions/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_004_parameter_untupling/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercises/exercise_004_parameter_untupling/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_005_extension_methods/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercises/exercise_005_extension_methods/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_006_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercises/exercise_006_using_and_summon/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_007_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercises/exercise_007_givens/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercises/exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_009_union_types/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercises/exercise_009_union_types/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_010_opaque_type_aliases/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercises/exercise_010_opaque_type_aliases/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- exercises/exercise_011_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/sudoku/SudokuProblemSender.scala
- exercises/exercise_011_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/sudoku/TopLevelDefinitions.scala
- Rename transpose to a domain specific meaning
- Formatting of an extension methods
> Refactoring base code

- exercises/exercise_000_sudoku_solver_initial_state/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercises/exercise_001_dotty_deprecated_syntax_rewriting/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercises/exercise_002_dotty_new_syntax_and_indentation_based_syntax/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercises/exercise_003_top_level_definitions/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercises/exercise_004_parameter_untupling/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercises/exercise_005_extension_methods/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercises/exercise_006_using_and_summon/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercises/exercise_007_givens/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercises/exercise_008_enum_and_export/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercises/exercise_009_union_types/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercises/exercise_010_opaque_type_aliases/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercises/exercise_011_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercises/exercise_020_opaque_type_aliases_alt/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
- exercises/exercise_021_multiversal_equality/src/main/scala/org/lunatechlabs/dotty/SudokuSolverMain.scala
> Fix typo in comment

- .github/workflows/ci.yml
- Release course using CMT 2 version of the tooling
> Adapt ci release process cmt 2

- README.md
- slides/00-title-page.md
- slides/01-introduction.md
- Added instructions for installing the Scala Center's "Scala 3 Migration Course"
- Added an introductions section
> Update main README & installation instructions

- exercises/exercise_000_sudoku_solver_initial_state/src/main/resources/application.conf
- exercises/exercise_001_dotty_deprecated_syntax_rewriting/src/main/resources/application.conf
- exercises/exercise_002_dotty_new_syntax_and_indentation_based_syntax/src/main/resources/application.conf
- exercises/exercise_003_top_level_definitions/src/main/resources/application.conf
- exercises/exercise_004_parameter_untupling/src/main/resources/application.conf
- exercises/exercise_005_extension_methods/src/main/resources/application.conf
- exercises/exercise_006_using_and_summon/src/main/resources/application.conf
- exercises/exercise_007_givens/src/main/resources/application.conf
- exercises/exercise_008_enum_and_export/src/main/resources/application.conf
- exercises/exercise_009_union_types/src/main/resources/application.conf
- exercises/exercise_010_exploring_opaque_type_aliases/src/main/resources/application.conf
- exercises/exercise_011_optional_opaque_type_aliases/src/main/resources/application.conf
- exercises/exercise_012_multiversal_equality/src/main/resources/application.conf
- exercises/exercise_020_opaque_type_aliases_alt/src/main/resources/application.conf
- exercises/exercise_021_multiversal_equality/src/main/resources/application.conf
- Set Pekko logging to use slf4j
> Configure pekko slf4j logging
